import sys
import os
from pathlib import Path
from nacl.signing import SigningKey
from nacl.encoding import HexEncoder

def generate_keys():
    print("Generating Cobo API Key Pair (Ed25519)...")
    
    # Generate new key pair using PyNaCl
    signing_key = SigningKey.generate()
    private_key = signing_key.encode(encoder=HexEncoder).decode('utf-8')
    public_key = signing_key.verify_key.encode(encoder=HexEncoder).decode('utf-8')
    
    print(f"Generated Public Key: {public_key}")
    
    # Path to .env file
    env_path = Path(__file__).parent.parent / '.env'
    
    # Read existing content if file exists
    env_content = ""
    if env_path.exists():
        with open(env_path, 'r') as f:
            env_content = f.read()
            
    # Check if keys already exist to avoid overwriting blindly (though requirements said append)
    # We will append or replace if they exist to ensure the new keys are used
    new_lines = []
    
    # Simple parsing to remove old keys if we want to be clean, but appending overrides in many env loaders.
    # However, python-dotenv usually takes the first one or last one depending on config.
    # Let's just append for now as requested, but maybe add a newline.
    
    with open(env_path, 'a') as f:
        f.write(f"\n# Generated by scripts/generate_keys.py\n")
        f.write(f"COBO_API_PRIVATE_KEY={private_key}\n")
        f.write(f"COBO_API_PUBLIC_KEY={public_key}\n")
        
    print(f"\nSUCCESS: Keys have been appended to {env_path}")
    print("----------------------------------------------------------------")
    print("IMPORTANT: COPY THIS PUBLIC KEY TO COBO DASHBOARD:")
    print(f"{public_key}")
    print("----------------------------------------------------------------")

if __name__ == "__main__":
    generate_keys()
